volumes:
  ekmek-vol:

services:
  db:
    image: postgres:16
    restart: always
    ports: 
      - 12345:5432
    volumes:
      - ekmek-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bot_db
      POSTGRES_USER: ps_user
      POSTGRES_PASSWORD: pass
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
